apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: cross-build-git
spec:
  type: git
  params:
    - name: revision
      value: main
    - name: url
      value: https://github.com/paolocarta/cross-building-containers.git
