apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-docker-image-from-git-source-pipeline-run
spec:
  # serviceAccountName: quay-service
  pipelineRef:
    name: build-ppc64le-image-from-tekton-pipeline
  resources:
    - name: cross-build-docker-source
      resourceRef:
        name: cross-build-git 
